{{- if .Values.controller.enabled -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: csi-provisioner
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: csi-provisioner
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  replicas: {{ .Values.controller.replicas }}
  template:
    metadata:
      labels:
        app: csi-provisioner
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
              - key: alibabacloud.com/is-edge-worker
                operator: NotIn
                values:
                - "true"
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - csi-provisioner
              topologyKey: kubernetes.io/hostname
      tolerations:
      - effect: NoSchedule
        operator: Exists
        key: node-role.kubernetes.io/control-plane
      - effect: NoSchedule
        operator: Exists
        key: node.cloudprovider.kubernetes.io/uninitialized
      serviceAccountName: alicloud-csi-provisioner
      hostPID: true
      priorityClassName: system-node-critical
      containers:
{{- if and .Values.csi.disk.enabled .Values.csi.disk.controller.enabled }}
        - name: external-disk-provisioner
          image: {{ include "imageSpec" (list .Values.images "externalProvisioner") }}
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 500m
              memory: 1024Mi
          args:
            - "--csi-address=$(ADDRESS)"
            - "--feature-gates=Topology=True"
            - "--volume-name-prefix=disk"
            - "--strict-topology=true"
            - "--timeout=150s"
            - "--leader-election=true"
            - "--retry-interval-start=500ms"
            - "--extra-create-metadata=true"
            - "--default-fstype=ext4"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/csi-provisioner/diskplugin.csi.alibabacloud.com/csi.sock
          volumeMounts:
            - name: disk-provisioner-dir
              mountPath: /var/lib/kubelet/csi-provisioner/diskplugin.csi.alibabacloud.com
        - name: external-disk-attacher
          image: {{ include "imageSpec" (list .Values.images "externalAttacher") }}
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 500m
              memory: 1024Mi
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--leader-election=true"
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/csi-provisioner/diskplugin.csi.alibabacloud.com/csi.sock
          volumeMounts:
            - name: disk-provisioner-dir
              mountPath: /var/lib/kubelet/csi-provisioner/diskplugin.csi.alibabacloud.com
        - name: external-disk-resizer
          image: {{ include "imageSpec" (list .Values.images "externalResizer") }}
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 500m
              memory: 1Gi
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--leader-election"
            - "--handle-volume-inuse-error=false"
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/csi-provisioner/diskplugin.csi.alibabacloud.com/csi.sock
          volumeMounts:
            - name: disk-provisioner-dir
              mountPath: /var/lib/kubelet/csi-provisioner/diskplugin.csi.alibabacloud.com
        - name: external-csi-snapshotter
          image: {{ include "imageSpec" (list .Values.images "externalSnapshotter") }}
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 500m
              memory: 1024Mi
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--leader-election=true"
            - "--extra-create-metadata=true"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: disk-provisioner-dir
              mountPath: /csi
        - name: external-snapshot-controller
          image: {{ include "imageSpec" (list .Values.images "externalSnapshotController") }}
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 500m
              memory: 1024Mi
          args:
            - "--v=5"
            - "--leader-election=true"
{{- end -}}
{{- if and .Values.csi.nas.enabled .Values.csi.nas.controller.enabled }}
        - name: external-nas-provisioner
          image: {{ include "imageSpec" (list .Values.images "externalProvisioner") }}
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 500m
              memory: 1024Mi
          args:
            - "--csi-address=$(ADDRESS)"
            - "--volume-name-prefix=nas"
            - "--timeout=150s"
            - "--leader-election=true"
            - "--retry-interval-start=500ms"
            - "--default-fstype=nfs"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/csi-provisioner/nasplugin.csi.alibabacloud.com/csi.sock
          volumeMounts:
            - name: nas-provisioner-dir
              mountPath: /var/lib/kubelet/csi-provisioner/nasplugin.csi.alibabacloud.com
        - name: external-nas-resizer
          image: {{ include "imageSpec" (list .Values.images "externalResizer") }}
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 500m
              memory: 1Gi
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--leader-election"
            - "--handle-volume-inuse-error=false"
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/csi-provisioner/nasplugin.csi.alibabacloud.com/csi.sock
          volumeMounts:
            - name: nas-provisioner-dir
              mountPath: /var/lib/kubelet/csi-provisioner/nasplugin.csi.alibabacloud.com
{{- end -}}
{{- if and .Values.csi.oss.enabled .Values.csi.oss.controller.enabled }}
        - name: external-oss-provisioner
          args:
            - --csi-address=$(ADDRESS)
            - --volume-name-prefix=oss
            - --timeout=150s
            - --leader-election=true
            - --retry-interval-start=500ms
            - --default-fstype=ossfs
            - --v=5
          env:
          - name: ADDRESS
            value: /var/lib/kubelet/csi-provisioner/ossplugin.csi.alibabacloud.com/csi.sock
          image: {{ include "imageSpec" (list .Values.images "externalProvisioner") }}
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 16Mi
          volumeMounts:
          - mountPath: /var/lib/kubelet/csi-provisioner/ossplugin.csi.alibabacloud.com
            name: oss-provisioner-dir
{{- end -}}
{{- if and .Values.csi.local.enabled .Values.csi.local.controller.enabled }}
        - name: external-local-provisioner
          image: {{ include "imageSpec" (list .Values.images "externalProvisioner") }}
          imagePullPolicy: Always
          env:
            - name: ADDRESS
              value:  /var/lib/kubelet/csi-provisioner/localplugin.csi.alibabacloud.com/csi.sock
          args:
            - --csi-address=$(ADDRESS)
            - --feature-gates=Topology=True
            - --volume-name-prefix=local
            - --strict-topology=true
            - --timeout=150s
            - --extra-create-metadata=true
            - --enable-leader-election=true
            - --leader-election-type=leases
            - --retry-interval-start=500ms
            - --default-fstype=ext4
            - --v=5
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 500m
              memory: 1024Mi
          volumeMounts:
            - name: local-provisioner-dir
              mountPath: /var/lib/kubelet/csi-provisioner/localplugin.csi.alibabacloud.com
        - name: external-local-resizer
          image: {{ include "imageSpec" (list .Values.images "externalResizer") }}
          imagePullPolicy: Always
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/csi-provisioner/localplugin.csi.alibabacloud.com/csi.sock
          args:
            - --v=5
            - --csi-address=$(ADDRESS)
            - --leader-election
          volumeMounts:
            - name: local-provisioner-dir
              mountPath: /var/lib/kubelet/csi-provisioner/localplugin.csi.alibabacloud.com
{{- end }}
        - name: csi-provisioner
          securityContext:
            privileged: true
          image: {{ include "imageSpec" (list .Values.images "controller") }}
          args:
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--v=2"
            - "--driver={{ include "enabledControllers" .Values.csi }}"
{{- if .Values.deploy.featureGates }}
            - "--feature-gates={{ .Values.deploy.featureGates }}"
{{- end -}}
{{- if not .Values.deploy.ecs }}
            - --nodeid=$(KUBE_NODE_NAME)
{{- end }}
          env:
            - name: CSI_ENDPOINT
              value: unix://var/lib/kubelet/csi-provisioner/driverplugin.csi.alibabacloud.com-replace/csi.sock
            - name: SERVICE_TYPE
              value: "provisioner"
{{- if .Values.deploy.ack }}
            - name: "CLUSTER_ID"
              value: {{ .Values.deploy.clusterID | quote }}
{{- end }}
{{- if .Values.deploy.regionID }}
            - name: REGION_ID
              value: {{ .Values.deploy.regionID | quote }}
{{- end }}
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
{{- if .Values.deploy.ecsEndpoint }}
            - name: ECS_ENDPOINT
              value: {{ .Values.deploy.ecsEndpoint | quote }}
{{- end }}
{{- if .Values.deploy.privateCloud }}
            - name: ALICLOUD_CLIENT_SCHEME
              value: HTTP
            - name: PRIVATE_CLOUD_TAG
              value: "true"
{{- end }}
            - name: ENABLE_NAS_SUBPATH_FINALIZER
              value: "true"
{{- if .Values.deploy.accessKey.enabled }}
            - name: ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.deploy.accessKey.secretName }}
                  key: id
            - name: ACCESS_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.deploy.accessKey.secretName }}
                  key: secret
{{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 5
            periodSeconds: 20
          ports:
            - name: healthz
              containerPort: 11270
          volumeMounts:
            - name: host-log
              mountPath: /var/log/
{{- range $key, $val := .Values.csi }}
{{- if and $val.enabled $val.controller.enabled }}
            - name: {{ $key }}-provisioner-dir
              mountPath: /var/lib/kubelet/csi-provisioner/{{ $key }}plugin.csi.alibabacloud.com
{{- end -}}
{{- end }}
{{- if .Values.deploy.ack }}
            - mountPath: /var/addon
              name: addon-token
              readOnly: true
{{- end }}
            - mountPath: /mnt
              mountPropagation: Bidirectional
              name: host-mnt
            - mountPath: /host/etc
              name: etc
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
{{- range $key, $val := .Values.csi }}
{{- if and $val.enabled $val.controller.enabled }}
        - name: {{ $key }}-provisioner-dir
          emptyDir: {}
{{- end -}}
{{- end }}
        - name: host-log
          hostPath:
            path: /var/log/
        - name: etc
          hostPath:
            path: /etc
            type: ""
        - name: host-mnt
          hostPath:
            path: /mnt
            type: ""
{{- if .Values.deploy.ack }}
        - name: addon-token
          secret:
            defaultMode: 420
            optional: true
            items:
            - key: addon.token.config
              path: token-config
            secretName: addon.csi.token
{{- end -}}
{{- end -}}
